### ISSUE TITLE
Pas de vérification du type sur les champs de saisie numériques

### ISSUE THREAD

**Issue by GllmR** [openpcrs/pcrs.beta.gouv.fr#144]
## Problème

Actuellement, les champs de saisie numériques ne vérifient pas le type d’entrée.

Lorsque l’utilisateur entre une chaine de caractère dans un champ numérique, aucun message d’erreur n’est affiché et la valeur est transformée en `N/A`.

## Reproduction

Sur la page de formulaire, entrer une chaine de caractère dans un champ de saisie numérique : 
La valeur de la chaine est transformée en `N/A` sans qu’aucun message ne soit envoyé à l’utilisateur.

**Comment by Maxine-Le-Pennec** [comment]
La méthode généralement appliquée pour corriger ce souci, implique d'utiliser un input de type `text` auquel on applique un filtre au `onChange`.

Cependant, cette méthode est contraire aux directives du DSFR
