### ISSUE TITLE
Modal d'auth : impossible de fermer

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#145]
Dans le modal d'authentification, obtenu au clic sur le bouton "éditer" d'un projet de la carte de suivi, il n'est pas possible de fermer.

Au clic, aucun effet produit et aucune erreur dans la console.

![image](https://user-images.githubusercontent.com/5690599/230057745-35a1b9a4-88f8-4611-b0b7-3d8f72a1833a.png)

**Comment by GllmR** [comment]
Je pense que c'est quelque chose de voulu, pour éviter de proposer le formulaire à un utilisateur qui n'aurait pas de jeton.

Cet événement est théoriquement impossible à reproduire depuis [la récente PR](https://github.com/openpcrs/pcrs.beta.gouv.fr/pull/139) qui masque les boutons d'édition lorsque le jeton n'est pas présent.

**Comment by flacombe** [comment]
C'est entendu, mais je pense que dans ce cas, il faudrait faire une redirection au clic sur le bouton fermer.

Pour ne pas laisser l'utilisateur frustré :)
