### ISSUE TITLE
Formulaire : au renommage d'un projet vers un nom existant, erreur javascript

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#168]
Au renommage d'un projet vers un nom identique à un autre projet existant, une erreur javascript n'est pas gérée dans le navigateur.
Elle survient à la validation du formulaire d'édition

![image](https://user-images.githubusercontent.com/5690599/232795668-c027b456-e0c6-4db2-81d4-057b8c801d8b.png)

On préférerait avoir un message d'erreur au bas du formulaire en indiquant que le nom existe déjà

**Comment by GllmR** [comment]
Idem à #148
