### ISSUE TITLE
Retourner un message d'erreur par l'API

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [openpcrs/pcrs.beta.gouv.fr#265]
Lors d'une requête, la réponse renvoyée par l'API ne retourne pas un message d'erreur clair en français.
Exemple : `statusText: "Not Found"`.

Deux solutions sont possibles : 

- soit l’API renvoi un message en français
- soit le code et le message sont captés par le front qui l'interprète pour l'utilisateur 

Le mieux étant que l’API, dédiée exclusivement au front du PCRS s'en charge.

**Comment by GllmR** [comment]
Tu peux préciser un peu ?

Par exemple, si tu fais une requête sur `/data/projets.csv`, ça ne renvoie pas un message d'erreur "Not Found".

**Comment by Maxine-Le-Pennec** [comment]
> @Maxine-Le-Pennec Tu peux préciser un peu ?
> 
> Par exemple, si tu fais une requête sur `/data/projets.csv`, ça ne renvoie pas un message d'erreur "Not Found".

Yes ! 
Ça a été remarqué sur la gestion des porteurs (et du coup repéré aussi sur la PR Ajout d’une API pour la gestion des administrateurs #253). C'est le front qui retourne une erreur générale pour le moment en cas d'échec. Théo a relevé que c'était mieux d'avoir des réponses plus précises à afficher.
