### ISSUE TITLE
Ne pas être dans la liste admin et pourtant ajouter des admins

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#287]
Hello

Je n'apparait pas dans la liste des admins et pourtant je peux en ajouter.
Je ne me souviens pas, on a pas supprimé le token global pour le remplacer par la liste ?

![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/2b80cf92-4bff-4de1-aac4-d724a98f8fd4)

Peut-etre est-ce une erreur de ma part :)

**Comment by GllmR** [comment]
Dans l’idée, le token "global" ne devrait plus être utilisé.
Il reste cependant en place pour permettre la création d’un premier administrateur.

J’attendais que tous les administrateurs soient créés avant de le mettre à jour, mais je peux le faire maintenant si tu penses que c’est nécessaire.

**Comment by flacombe** [comment]
Oui @GllmR, je viens de compléter la liste des admins et nous pouvons donc supprimer le token global asap s'il te plaît.

**Comment by GllmR** [comment]
C’est fait !
