### ISSUE TITLE
Passage au modèle de données 0.4

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#310]
Bonjour tout le monde.

J'ouvre cette issue ici pour y regrouper tout ce qui touche au passage au modèle de données 0.4.
Le document de travail a été donné en lien dans nos précédents échanges (doc privée, je ne peux pas le mettre ici).

@GllmR pourras-tu m'indiquer une date qui t'arrange pour faire la migration, en fonction des autres devs en cours pour que je m'accorde en mettant à jour la doc publique s'il te plait ? (et que je fasse les annonces de rigueur).

**Comment by flacombe** [comment]
A noter que certains champs, indiqués en rouge sur cette page passeront en deprecated dans la structure des fichiers publiés sur data.gouv

Concrètement pour cette version on les laisse dans les fichiers sous la forme de valeurs vide
https://app.gitbook.com/o/eGaKyLf7dXVwwD1Orrwq/s/DLJUeVYg0AGH6AXMN2MW/portail-pcrs/suivi-des-projets#livrables

**Comment by flacombe** [comment]
La liste l_pcrs_compression a été ajoutée, sur la bibliographie minimale dont je disposais.
On peut la compléter/modifier parce que je ne pense pas tout avoir @cedric-famibelle-pronzola @jdesboeufs 
https://app.gitbook.com/o/eGaKyLf7dXVwwD1Orrwq/s/DLJUeVYg0AGH6AXMN2MW/portail-pcrs/modeles-de-donnees#compression-des-livrables

La nature des livrables a été passée en mime @GllmR 
https://app.gitbook.com/o/eGaKyLf7dXVwwD1Orrwq/s/DLJUeVYg0AGH6AXMN2MW/portail-pcrs/modeles-de-donnees#nature-des-livrables

**Comment by flacombe** [comment]
Vu les modifications sur les paramètres de stockage dans les livrables. Aucun problème.
Pourquoi pas de Digest dans la méthode @GllmR ? Basic est deprecate non ?

**Comment by GllmR** [comment]
Fait dans la branche `model-v0.4`
