### ISSUE TITLE
Travail préparatoire du front concernant le scanner de fichier

### ISSUE THREAD

**Issue by Maxine-Le-Pennec** [openpcrs/pcrs.beta.gouv.fr#313]
Plusieurs étapes de préparations sont nécessaires afin d'intégrer la fonctionnalité de scan de fichier :

- [x] Supprimer le champ `Publication` dans les mini-form `livrable` du formulaire de suivi
![Capture d’écran 2023-10-03 à 17 55 46](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/4beade88-938b-41a3-9e64-494656b50ac3)

- [ ] Afficher la liste complète des livrables dans une modale depuis la sidebar de la page de suivi du pcrs
![Capture d’écran 2023-10-03 à 17 56 59](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/c10e31f7-313e-4aa2-a162-678c3292f9c2)

- [ ] Créer un composant permettant l'affichage d'une arborescence de fichiers

![Capture d’écran 2023-10-03 à 17 57 46](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/42656d77-0b52-4b87-b012-43dad697ac6e)

- [x] Ajouter les champs d'ajout de source pour chaque livrable dans le formulaire de projet

![Capture d’écran 2023-10-03 à 17 59 05](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/5b99e45b-c474-4fc6-b1fc-8345e8026404)

- [x] Création d'un formulaire d'authentification vers l'accès aux sources

![Capture d’écran 2023-10-03 à 17 59 35](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/c2021fd9-f3b7-4038-ac3b-201d8ed6b9c3)

- [x] Création d'un composant affichant les informations scannées à partir d'un fichier

![Capture d’écran 2023-10-03 à 18 00 46](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/3692a79b-e865-4298-b3a9-d355b05daf45)

- [ ] Création layout responsive permettant d'afficher l'arborescence de fichiers + infos fichiers

![Capture d’écran 2023-10-03 à 18 01 19](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/bf2be310-8014-42c1-8695-67788f39060d)
![Capture d’écran 2023-10-03 à 18 01 10](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/f6b788ad-924b-4d8f-b4be-c219a54d91eb)

- [ ] Création page Ressources des livrables

![Capture d’écran 2023-10-03 à 18 02 06](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/66621960/58bdb7e9-f43e-4ade-9c34-e6c9fe5d98c6)

**Comment by GllmR** [comment]
Ok suite au merge de la branche `model-v0.4`
