### ISSUE TITLE
Bug : cliquer sur un projet sur la carte mène à un 404

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#317]
Hello

Au clic d'un projet sur la carte, j'ai un 404 au lieu d'avoir le panneau de gauche.
C'est un soucis :)

**Comment by tmerlier** [comment]
Je ne parviens pas à reproduire. C'est sur un projet en particulier ? Je suis preneur de toute info supplémentaire pour permettant d'identifier le problème.

**Comment by flacombe** [comment]
C'est sur tout les projets, je me prends des 403 de l'API semble-t-il : 
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/bf729cfe-defb-42cb-8528-8a0b48fa99ea)

**Comment by flacombe** [comment]
Non, ce n'était pas pour modifier quoi que ce soit, c'était juste l'accès en lecture à la carte des projets sur https://pcrs.beta.gouv.fr/suivi-pcrs

Il n'y a normalement pas besoin d'être authentifié pour cette partie

**Comment by GllmR** [comment]
Si ton jeton n'est pas bon, le site empêche l'affichage (à cause des boutons dans la sidebar).

Il faudrait corriger ça effectivement.

Est-ce que tu as le même problème en navigation privée ?

**Comment by flacombe** [comment]
Non, il est vrai : ça fonctionne en navigation privée.

J'ai mis le bon token et ca fonctionne.
Il faudrait alors afficher une notif ou une erreur plus explicite à l'utilisateur que son token à expirer je pense

**Comment by GllmR** [comment]
Tout à fait, je suis en train de rédiger une issue à ce sujet.

Si ça te va, je ferme celle-ci dès que l’issue est en ligne.

**Comment by GllmR** [comment]
Je dirais que le mieux serait d’afficher le panneau latéral sans les boutons, comme pour un utilisateur "normal".

Il y a plusieurs pistes à explorer, je n’ai pas encore regardé ce qu’il se passe précisément dans le cas que tu as découvert.

**Comment by GllmR** [comment]
Je ferme cette issue, une nouvelle issue expliquant le problème plus précisément a été ouverte [ici](https://github.com/openpcrs/pcrs.beta.gouv.fr/issues/320)
