### ISSUE TITLE
Calculatrice : message d'erreur à la saisie de la taille d'un fichier

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#331]
Bonjour,

Il y a un soucis de validation dans la saisie de la taille d'un fichier sur la calculatrice
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/428ac568-96c6-4456-bfae-a9aed3510029)

**Comment by GllmR** [comment]
Il semble que ce bug ait été corrigé par une récente mise à jour des inputs.

**Comment by flacombe** [comment]
Je confirme, merci !
