### ISSUE TITLE
Capacité à relancer manuellement un scan de stockage

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#363]
Hello

Dans nos précédentes discussions, je me demandais si il était possible de disposer d'un contrôle dans le formulaire projet permettant au porteur de projet de relancer un scan ponctuel de son stockage en dehors de la régularité mensuelle.

Visiblement la route API est prévue sur le scanner de fichiers.
Quelle serait la charge nécessaire pour ajouter ce contrôle et permettre à l'utilisateur de rescanner son espace plus rapidement ?

Cela sera forcément demandé, lorsque les porteurs de projets mettent à jour leurs fichiers.
Si cela est possible, ajoutez le maintenant svp

**Comment by flacombe** [comment]
Une question gestion des accès : comment l'accès à cette route de relance du scan est-il autorisé ?

Est-ce qu'il y a un éventuel moyen de contrôler que l'appel se fait bien depuis la page utilisée pa le porteur du lien d'édition du projet ?
Sachant bien que le scanner de fichiers est un composant séparé du site PCRS, à juste titre, ce serait probablement bizarre de les lier trop fortement.

Peut-être que mon interrogation n'est pas la bonne.

**Comment by flacombe** [comment]
Ce qui semble le plus impératif d'interdire est qu'un porteur de projet sur un territoire A puisse intervenir sur les scan du territoire B sur lequel il n'a pas de droits.

Ainsi si l'un des porteurs de projet capture le jeton de connexion à l'API et connaît l'id d'un autre projet duquel il n'a pas le lien d'édition, peut-il relancer le scan ? (normalement non).

**Comment by GllmR** [comment]
Non, il est impossible de trouver le jeton qui connecte la partie backend du site et l'api-scanner.

La relance du scan se fait depuis le formulaire, donc depuis le lien d'édition, seule une personne autorisée à modifier un projet pourra relancer le scan.

**Comment by flacombe** [comment]
Ah super, c'est tout bon dans ce cas !
(l'issue reste ouverte le temps d'ajouter le bouton)

**Comment by GllmR** [comment]
Corrigé par #364
