### ISSUE TITLE
Référencement commune des Trois Lacs (27058 / 27676)

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#400]
Il y a un soucis dans le référencement de la commune des Trois Lacs dans l'Eure.
Elle est introuvable sous le code INSEE 27065 et existe sous le code 27676.

L'ajout de la commune 27676 génère un geojson invalide et une erreur 500 à l'appel de https://pcrs.beta.gouv.fr/projets/geojson

Peut-être cela vient-il de geo.api.gouv.fr ?

Dans l'attente on a un trou dans une anticipation Enedis
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/63b5793e-bc97-4be2-ada7-7beb22600f95)

**Comment by jdesboeufs** [comment]
Le millésime du COG et des contours administratif actuellement utilisé est celui de 2022.
La commune est bien présente sous son code officiel 27676.

L'outil ne supporte pas les communes déléguées à ce stade.
