### ISSUE TITLE
Scan des fichiers PCRS GeoTiff, erreur `not a valid IFD offset`

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#401]
Récemment un territoire qui souhaite déclarer un livrable stocké sur ses serveurs auprès du scanner de livrables rencontre une erreur qui se manifeste par l'ensemble des fichiers rejetés sur la page projet
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/ce11a7c7-aa80-4e9e-ac48-2e11289abd34)

Deux problèmes se posent alors :

- L'information partielle de l'utilisateur qui ne peut pas savoir en quoi l'erreur consiste. Sera traité en roadmap => #386 
- L’occurrence même des erreurs, sur des fichiers GeoTiff

D'après investigations, on voit la mention suivante dans les logs `TIFFFetchDirectory:Sanity check on directory count failed, this is probably not a valid IFD offset`
A investiguer pour comprendre d'où ca vient.

**Comment by jdesboeufs** [comment]
Problème avec les fichiers GeoTIFF corrigé via https://github.com/openpcrs/pcrs-scanner/commit/39a7bb405c05dee6ad27acc918876d95d6b8a023.

<img width="904" alt="Capture d’écran 2024-02-21 à 23 27 57" src="https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/1231232/f6d6613a-ebc9-4791-8b8a-18ec44340405">

**Comment by flacombe** [comment]
Super !

Pour moi c'est bon, je vais remonter le soucis sur les 10 fichiers en erreurs.

Merci beaucoup
