### ISSUE TITLE
Scan des fichiers PCRS JPEG2000 via HTTP IIS : impossible de récupérer les ressources carto

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#402]
Hello

Nous avons un nouveau cas de test sur un PCRS JPEG2000 publié en HTTP.
https://pcrs.beta.gouv.fr/projet/64281c3f4340ffbf17bf2e66
Le répertoire est bien accessible, vérifié dans mon navigateur.

Le stockage est déclaré dans le projet et le scan a été demandé via le bouton du formulaire.
Nous voyons le résultat suivant sur la page projet.
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/bc736350-ff57-4c6b-8b77-84a3d6fa72ac)

Est-ce parce que le scan échoue ou qu'il n'a pas encore eu lieu ?
Si cela venait des fichiers présents dans le répertoire, nous aurions le nombre ainsi que les erreurs je pense, comme dans #401

**Comment by flacombe** [comment]
Hello est-ce que le correctif nécessaire à l'intégration des index HTTP Windows a été déployé ?

**Comment by jdesboeufs** [comment]
Le correctif concernant IIS a été déployé le 7 mars dernier.
