### ISSUE TITLE
Disparition des résultats d'un scan et impossible de relancer

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#403]
Sur l'un des territoires précédemment connecté aux fonctionnalités de publication des livrables, les résultats n'apparaissent plus sur la page projet et il n'est pas possible de relancer un scan.
https://pcrs.beta.gouv.fr/projet/64281c3f4340ffbf17bf2e30

Les informations de connexion sont bien renseignées.
![Capture d’écran du 2024-03-13 15-00-15](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/4e09b15f-64cc-4e63-81e2-680a5a3fa452)

Il y a un message au re-lancement du scan
![image](https://github.com/openpcrs/pcrs.beta.gouv.fr/assets/5690599/d334686b-db72-45ab-bfc1-10f2301ad43f)

L'utilisateur n'est pas autonome pour régler le problème.

**Comment by flacombe** [comment]
Nous aurions vraiment besoin de débloquer ce projet s'il vous plaît, il n'est plus en ligne depuis près d'un mois et ac empêche de s'en servir comme exemple.

A noter que les géométries sont aussi absentes des données brutes, ce qui est cohérent.

**Comment by flacombe** [comment]
D'après nos discussions, il semble que des espaces puissent apparaître dans les valeurs des champs sans être trimés.
Cela empêche la création ou le rattachement aux stockages existants, cause de l'erreur rencontrée ici.

**Comment by jdesboeufs** [comment]
Après vérification l'erreur indiquée ne se produit que si on demande la relance d'un scan d'un stockage qui n'est pas rattaché au projet.
C'est probablement un bug dans l'interface.

**Comment by jdesboeufs** [comment]
Le bug est corrigé. Le processus de recréation du stockage était bloqué par un ancien scan jamais nettoyé.
Plusieurs aménagement dans le backend et le scanner ont été plus en place pour fiabiliser la chaîne.
