### ISSUE TITLE
Téléchargement impossible de tuiles sur un projet déjà scanné : erreur not found ou timeout

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#410]
Nous rencontrons un soucis sur l'exploration d'un projet déjà scanné et dont le téléchargement etait possible jusqu'à maintenant.
https://pcrs.beta.gouv.fr/projet/64281c3f4340ffbf17bf2e8a

Au téléchargement d'une dalle, on obtient une erreur "Not found" ou un timeout scalingo sans plus de précisions.
Est-ce le serveur partenaire qui ne répond pas ?

Exemple : https://scanner.pcrs.beta.gouv.fr/storages/65796d005cefa92abc4ebdd8/files//pcrs_syaden/11_Chantier_B/4_Orthophotographie/11_blocB_Dalles_RVB/11-2021-0661-6226-LA93-0M05-RVB-E100.jp2?token=undisclosed

**Comment by flacombe** [comment]
C'est un problème coté porteur de projet, le répertoire du stockage distant est vide.

Je fais le point avec le porteur de projet avant de fermer ce ticket

**Comment by Gab-OPenIG** [comment]
Je point de montage était démonté et j'ignore pourquoi. C'est un point de montage virtuel, nous ne répliquons pas les dalles.  Je l'ai remis en place et cela semble visible de mon côté. De chez vous ça remonte ?

**Comment by flacombe** [comment]
Merci beaucoup @Gab-OPenIG, ca fonctionne à nouveau !

**Comment by Gab-OPenIG** [comment]
Hmmm... ça ne télécharge pas chez moi. Cela fonctionne chez vous ?

**Comment by flacombe** [comment]
Je confirme @Gab-OPenIG ca timeout à nouveau ce matin.
Le montage chez vous est-il toujours monté ?

**Comment by Gab-OPenIG** [comment]
Oui il n'a pas bougé depuis hier

**Comment by flacombe** [comment]
Chez moi aussi, on va y arriver !

**Comment by flacombe** [comment]
Hello @Gab-OPenIG, ce matin nous avons à nouveau des timeout.
Est-ce que le point de montage est bien actif ?

**Comment by Gab-OPenIG** [comment]
Salut @flacombe, j'ai vu que c'était up pour ma part, et j'ignore si ton timeout est lié à cela mais notre hébergeur subit des pannes (il est à Carcassonne) et il y a eu hier un incendie bloquant la circulation ferroviaire pas loin (Castelanudary)... Actuellement, notre VPN est par terre, et je ne peux don pas consulter l'état de nos ressources.

**Comment by flacombe** [comment]
Merci @Gab-OPenIG pour l'info sur l'incident en cours en effet.
Je pense que c'est durablement rétabli, fermons donc cette issue :p
