### ISSUE TITLE
Concurrence des stockages entre deux projets du même territoire

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#432]
D'après les retours que nous avons sur le territoire de la CC de Haguenau, il y aurait un conflit sur un serveur SFTP utilisé pour deux projets différents.
Les deux projets sont distingués par des répertoires différents sur ce serveur et le scanner n'en scanne qu'un des deux.

[Le premier projet](https://pcrs.beta.gouv.fr/projet/64281c3f4340ffbf17bf2de8) est correctement scanné et [le second projet](https://pcrs.beta.gouv.fr/projet/66265791b39c4f680e2ad7ef) est inaccessible avec les messages habituels d'impossibilité de lancer le scan.

Il semblerait qu'il soit nécessaire d'inclure le répertoire dans l'identifiant du scan et pas seulement l'hôte/port.
Même si c'est le même serveur, le répertoire joue un rôle important.
Peut-être que ce diagnostic est erroné.

**Comment by jdesboeufs** [comment]
Le diagnostic a peu de chance d'être correct car les stockages sont complètement indépendants.

Je vais regarde ça.

**Comment by flacombe** [comment]
Merci

Il faudra sûrement grouper le traitement de ce problème avec #403

**Comment by jdesboeufs** [comment]
Corrigé. C'est bien lié à #403.

**Comment by flacombe** [comment]
Je vois toujours une erreur sur le projet concerné : https://pcrs.beta.gouv.fr/projet/66265791b39c4f680e2ad7ef

Il semble qu'il faille merger #426 pour que ce soit effectivement corrigé non ?

**Comment by jdesboeufs** [comment]
Ça n'a rien à voir avec l'issue en tout cas

**Comment by flacombe** [comment]
Je ne vois pas d'autre PR et l'erreur est toujours présente, en quoi a consisté le fix et comment allons-nous voir ses effets ?

**Comment by GllmR** [comment]
> Je ne vois pas d'autre PR et l'erreur est toujours présente, en quoi a consisté le fix et comment allons-nous voir ses effets ?

La #426 évite que l'utilisateur puisse entrer un titre avec des espaces (par exemple " projet", 
elle ne corrige pas un bug, elle évite simplement les erreurs.

**Comment by flacombe** [comment]
C'est réglé, les deux projets sont bien scannés désormais
