### ISSUE TITLE
Scan échoué sur projet Terre de Provence

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#438]
Bonjour

Le scanner échoue à scanner le stockage positionné sur le livrable du projet Terre de Provence.
Le scan a été demandé mais nous avons le message d'erreur sur la page projet.
https://pcrs.beta.gouv.fr/projet/643ea1b45f8f7e62c19387ad

Nous sommes sollicités par le CRIGE PACA qui déploie le serveur concerné.

Peut-on indiquer ce qui bloque et comment le résoudre s'il vous plaît ?

**Comment by stephanerolle** [comment]
Bonjour,
Merci, j'attends le go pour aller plus loin sur les autres territoires.

**Comment by flacombe** [comment]
Hello @stephanerolle 

C'est réglé, désormais les tuiles s'affichent correctement.
Le problème venait du nom d'hôte saisi qui ne devait pas comporter le protocole. Je comprends que ce soit rageant de buter sur un détail comme cela, nous allons améliorer la doc et l'interface pour que ce soit plus fluide.

**Comment by stephanerolle** [comment]
Bonjour @flacombe
 
Merci pour le correctif, cela me semble ok.
Peu importe si cela a pris du temps, le but est que ce soit fonctionnel ;) .

**Comment by flacombe** [comment]
Très bien !

N'hésites pas à me dire si tu as des soucis pour les autres territoires

**Comment by flacombe** [comment]
Hello @stephanerolle 

J'ai demandé une relance du scan ce matin et c'est passé : https://pcrs.beta.gouv.fr/projet/643ea33e5f8f7e62c19387ae
Peut-être que @jdesboeufs sera intéressé pour tracer le log de ce qu'il s'est passé il y a 20 heures.

**Comment by stephanerolle** [comment]
Merci! 
Je pense savoir ce qu'il s'est passé.
J'avais oublié de transférer l'index des tuiles avant de cliquer sur valider. Je l'ai fait après coup.
le scan a du se lancer sans l'index et donc passer en échec.

**Comment by stephanerolle** [comment]
Bonjour @jdesboeufs @flacombe ,
Est il possible de relancer le scan pour le territoire CA ACCM (Arles), tout est en ligne.
Merci

**Comment by flacombe** [comment]
Bonjour @stephanerolle 

C'est fait aujourd'hui et 'c'est désormais en ligne !
Je passe donc le projet en disponible

J'espère que tout est bon pour toi ?
Restons en contact pour la suite des événements sur la métropole Aix-Marseille.

**Comment by stephanerolle** [comment]
C'est bon pour moi. Merci
Si besoin d'appui pour la métropole fais moi signe (mais c'est en ligne non?).

**Comment by flacombe** [comment]
C'est en ligne parce qu'on pointe vers la page de téléchargement de la métropole mais on ne peut pas le scanner parce que les dalles sont dans des répertoires zip par commune.
Il faudrait avoir un serveur de fichiers identiques aux votres
