### ISSUE TITLE
Réolution et millésime des contours administratifs

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#447]
Hello @jdesboeufs @GllmR 

Une question à propos du millésime et résolution des contours administratifs utillisés et les actions nécessaires à leur maintenant.

Ici (https://github.com/openpcrs/pcrs.beta.gouv.fr/blob/main/scripts/download-contours.js#L15) je vois que nous utilisons le millésime 2022 à la résolution 100m.
Est-ce que cela aurait un impact de changer cette valeur sur le millésime 2024 ou de changer la résolution ?

Les contours des projets doivent être stockés en base, donc à la prochaine validation d'un formulaire d'édition, les nouveaux contours administratifs seraient utilisés, c'est ça ?

Surement lié à #400

**Comment by jdesboeufs** [comment]
Il peut y avoir un impact sur les communes nouvelles dans le cas où la commune nouvelle ne serait pas totalement couverte par un projet PCRS.
Même problème avec les changements d'EPCI étant donné qu'on liste par EPCI.

**Comment by flacombe** [comment]
C'est vrai pour ces points.
On devrait enregistrer le dernier millésime utilisé dans le projet (si ce n'est pas déjà fait) et demander à l'utilisateur de valider explicitement les territoires employés lors de son prochain passage sur le formulaire (évolution à envisager).

Peux-tu me confirmer que ces changements s'opèrent au moment où on valide le formulaire à nouveau et qu'un changement de millésime ne modifie pas en masse tous les projets déclarés jusque là s'il te plaît ?

**Comment by flacombe** [comment]
De ce que j'ai compris de nos discussions, voici les points importants :
* Un changement d'échelle de 100m à 5m dans les périmètres administratifs entraînerait un surcroît de données à stocker, 500 Mo environ pour la base de données internes et environ autant pour l'export csv. L'architecture actuelle ne le permet pas
* Stocker le millésime ayant servi à l'élaboration du périmètre du projet est suffisant pour afficher un message d'information dans le formulaire et la page projet en cas de changement à la discrétion de l'administrateur
* Une évolution de millésime ne semble pas défoncer la carte web de suivi

Nous n'allons donc pas affiner la résolution des périmètres administratifs et poursuivre dans le sens de #456 et de #467
