### ISSUE TITLE
Le budget n'est pas pris en compte dans le formulaire

### ISSUE THREAD

**Issue by flacombe** [openpcrs/pcrs.beta.gouv.fr#480]
Le champ `budget` des informations générales n'est pas validé ni sa valeur transmise lors de la soumission du formulaire.

Le champ n'est pas visible dans le json qui est envoyé au serveur.
Je me demande en quoi [cette ligne](https://github.com/openpcrs/pcrs.beta.gouv.fr/blob/main/components/suivi-form/general-infos.js#L70) est utile si le champ n'est pas lui-même obligatoire ?

**Comment by GllmR** [comment]
C'est normal ici, c'est ce qui sert à remplir le champ budget du formulaire.

Le problème doit venir d'ailleurs, je jette un œil et je te dis.

**Comment by GllmR** [comment]
Ok, il faut ajouter `budget: suiviBudget` [ici](https://github.com/openpcrs/pcrs.beta.gouv.fr/blob/9dc2e576e815a427f3e65260ae518128ecb189f1/components/suivi-form/index.js#L130)

C'est bizarre qu'on ai pas vu ça avant 🫣
